### ISSUE TITLE
Stray file sbnanaobj/StandardRecord/LinkDef.h

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/sbnanaobj#12]
The file `sbnanaobj/StandardRecord/LinkDef.h` has, as far as I know, no role in generating ROOT dictionaries with GenReflex (or whatever the system pulled in by `cet_build_tools` is called).
Unless we are trying to support some other build system at the same time, this file should be removed to avoid confusion.
Please experts cross-check this statement...

Here is the blamed file:
https://github.com/SBNSoftware/sbnanaobj/blob/8ebb985392ccc5ae9b556a0487f42d0bceaf35db/sbnanaobj/StandardRecord/LinkDef.h

**Comment by cjbackhouse** [comment]
Yep, this will have been inherited from the NOvA StandardRecord, where it has also been redundant for years.
